### ISSUE TITLE
11章百度地图的代码运行出错

### ISSUE THREAD

**Issue by WindFromFarEast** [guolindev/booksource#11]
Information:Gradle tasks [:app:clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:assembleDebug]

Error:warning: Ignoring InnerClasses attribute for an anonymous inner class 
Error:(com.baidu.lbsapi.auth.d) that doesn't come with an 
Error:associated EnclosingMethod attribute. This class was probably produced by a
....
怎么样都解决不了，有人也遇到了吗？

**Comment by TzPersonalGH** [comment]
我也遇到了这个问题，唉，不知道怎么解决啊

**Comment by edsonJiao** [comment]
问一下你解决了吗

**Comment by guolindev** [comment]
这个只是个警告，是百度地图SDK内部造成的，不影响运行。
