### ISSUE TITLE
关于Kotlin版本

### ISSUE THREAD

**Issue by q269015385** [guolindev/booksource#15]
首先我很抱歉没有购买正版《第一行代码：第二版》，因为我非常喜欢在电脑上阅读电子版（颈椎问题）。目前kotlin语言已经出来了，而且谷歌积极的推荐开发者使用kotlin语言，我没学过java，只是了解过kotlin的语法、面向对象懂一点。虽然跟着这本书能正常学下去，但是有时候遇到java的代码，我还要翻译成kotlin的不然有的时候会报错。对我来说稍微有一点吃力，但是我最终还是能解决。我相信可能不止一个人遇到这个问题，所以我想说的重点是：作者可以再发布一版《第一行代码：kotlin版》？？期待！！

**Comment by Crazyya** [comment]
根据kotlin官网的文档摸索是学得最精的方式，师傅领进门，《第一行代码》就是这个师傅，剩下的不能说再一口一口喂给你知识吧，终究还是要靠自己的，当然，这只是我的想法，只是给个建议而已

**Comment by duxingzhe** [comment]
github上有许多从简单到复杂的kotlin应用，Google Play有很多kotlin教学APP，百度有很多关于kotlin入门的文章。

**Comment by guolindev** [comment]
未来可能会出的，等kotlin逐渐普及的时候，短期暂时还没有这个计划。

**Comment by hellohejinyu** [comment]
http://www.ituring.com.cn/book/1841
电子书也是有正版的，而且便宜不少
