### ISSUE TITLE
2.4.5 活动的回收

### ISSUE THREAD

**Issue by canalStar** [guolindev/booksource#18]
2.4.5节，按照书中的说明与例子写了app，但运行app时发现，onSaveInstanceState被调用后，savedInstanceState却一直为空，相应的调试信息也从未在catlog里打印出来，有大神知道这是什么情况吗？

**Comment by guolindev** [comment]
为空说明你的activity并没有被回收，这个方法只会在activity回收之前调用，然后再重新创建的时候savedInstanceState才会有值
