### ISSUE TITLE
按代码敲定位地址默认在北京怎么修改

### ISSUE THREAD

**Issue by Joyrocky** [guolindev/booksource#20]
希望有大佬指点

**Comment by whuhuanght** [comment]
可以参考 #19 ，或者改成如下的代码：
<pre>
private void navigateTo(BDLocation location) {  
    if (isFirstLocate) {  
        LatLng ll = new LatLng(location.getLatitude(), location.getLongitude());  
        MapStatusUpdate update = MapStatusUpdateFactory.newLatLngZoom(ll, 16f);  
        baiduMap.animateMapStatus(update);  
        isFirstLocate = false;  
    }  
} 
</pre>

**Comment by Joyrocky** [comment]
@whuhuanght 
`public void navigateTo(BDLocation location)
    {

        lat=location.getLatitude();
        lon=location.getLongitude();
        rad=location.getRadius();

        if(isFirstLocate)
        {
            setMarker();
            LatLng ll=new LatLng(lat,lon);

            //定义地图状态
            MapStatus mMapStatus = new MapStatus.Builder()
                    .target(ll)
                    .zoom(18)
                    .build();

            //定义MapStatusUpdate对象，以便描述地图状态将要发生的变化
            MapStatusUpdate mMapStatusUpdate = MapStatusUpdateFactory.newMapStatus(mMapStatus);

            //改变地图状态
            baiduMap.setMapStatus(mMapStatusUpdate);
            
            /*******第二种写法******/
           /*
            MapStatusUpdate update= MapStatusUpdateFactory.newLatLng(ll);
            baiduMap.animateMapStatus(update);//将地图移动到指定经纬
            update=MapStatusUpdateFactory.zoomTo(16f);
            baiduMap.animateMapStatus(update);//完成缩放功能
            */

            isFirstLocate=false;
        }`
两种写法都试过了，还是在北京，不知道是什么原因？

**Comment by whuhuanght** [comment]
你贴出来的第二种写法就是书上用不了的写法……第一种写法我亲测是可行的，可能是其他地方出了问题。

**Comment by Joyrocky** [comment]
我下了LBSTes做t测试，感觉是百度sdk的问题，用最新的版本会出来默认的北京地图，换之前的版本却是白板。

**Comment by dear-john** [comment]
option.setCoorType("bd09ll");
加上这一句应该就行了。
