### ISSUE TITLE
有关第9章第二节的代码问题

### ISSUE THREAD

**Issue by Ag-H2O** [guolindev/booksource#22]
一开始我用的url为www.baidu.com但是点击Button发现textView没有HTML内容出现，我添加日志如图一
![2018-01-06_170333](https://user-images.githubusercontent.com/25642544/34638301-b532b2d0-f303-11e7-8a9b-ef1e23536a49.png)

调试后图二
![2018-01-06_170414](https://user-images.githubusercontent.com/25642544/34638310-f1d8c012-f303-11e7-9607-540e73a2bc04.png)
换了网站url之后程序能运行了，但是
![screenshot_2018-01-06-17-09-27](https://user-images.githubusercontent.com/25642544/34638938-010379e4-f311-11e7-9cda-7ce3b4d394b6.png)

我想问下问什么会出现这种302 Found的现象呢

**Comment by guolindev** [comment]
因为网址不对，恰好你用来测试的两个网址都有问题。
第一个百度的网址在书出版之后改了，http已被废弃，要用https://www.baidu.com 才行
第二个新浪的网址从来都是 http://www.sina.com.cn
我们平时在浏览器输网址不需要这么严苛，因为浏览器会帮我们做自动跳转，这个302就是重定向的意思。

**Comment by Ag-H2O** [comment]
感谢您为我的解答

在 2018年1月15日 下午1:50，郭霖 <notifications@github.com>写道：
