### ISSUE TITLE
Chapter 5.5 Broadcastbestpractice BaseActivity

### ISSUE THREAD

**Issue by icmpnorequest** [guolindev/booksource#23]
您好，我在敲这个代码的时候，报错 BaseActivity is not in AndroidManifest，查看您的代码里也没有在AndroidManifest中定义BaseActivity，请问这个错误怎么解决？

**Comment by CNHTT** [comment]
where？？？  can you point out your problem in detail?

**Comment by guolindev** [comment]
楼上是正解。
