### ISSUE TITLE
第十二章material design

### ISSUE THREAD

**Issue by Chulinet** [guolindev/booksource#24]
写到外观功能与ActionBar一致那儿还没加按钮啥的，一运行就直接停止运行，代码和书上一样的，怎么解决啊

**Comment by lin1377434664** [comment]
看你有问题，特意上线来回复，有个问题你其实需要注意一下的，使用toolbar是需要设置一个noactionBar的主题的，你可能没注意。

**Comment by Chulinet** [comment]
非常感谢你的解答，已经解决了，是我自己太疏忽，xml里.不小心敲成了:
