### ISSUE TITLE
bing每日一图的api负载过高关闭了

### ISSUE THREAD

**Issue by envyandgreed** [guolindev/booksource#3]
可以讲一讲直接获取bing壁纸的方法么

**Comment by TonnyL** [comment]
@envyandgreed Maybe you could get more apis at [Awesome_APIs](https://github.com/TonnyL/Awesome_APIs).

**Comment by HanSircoming** [comment]
Android新手不知道咋弄！能具体的展现一下吗？

**Comment by guolindev** [comment]
这是一个服务器bug，现已修复。
