### ISSUE TITLE
使用最新版的Android Studio，出现ERROR: Failed to resolve: com.android.support:appcompat-v7:24.2.1

### ISSUE THREAD

**Issue by ZhangXinNan** [guolindev/booksource#35]
ERROR: Failed to resolve: com.android.support:appcompat-v7:24.2.1
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app

WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app

WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app

WARNING: The specified Android SDK Build Tools version (24.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.0.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '24.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Remove Build Tools version and sync project
Affected Modules: app

**Comment by yinliao173** [comment]
路过

**Comment by eruca** [comment]
怎么解决？

**Comment by easyasd** [comment]
'compile'替换为'implementation'

**Comment by wooodypan** [comment]
2020-12-09
Redmi K30 5G
Android 10

app目录的build.gradle
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "com.example.servicebestpractice"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:24.2.1'
    implementation 'com.squareup.okhttp3:okhttp:3.4.1'
}

```






根目录的build.gradle
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
