### ISSUE TITLE
天气返回的json中已经没有AQI 字段了

### ISSUE THREAD

**Issue by lvcAI** [guolindev/booksource#4]
`{
    "basic":Object{...},
    "daily_forecast":Array[3],
    "hourly_forecast":Array[2],
    "now":Object{...},
    "status":"ok",
    "suggestion":Object{...}
}`

这是现在的。

**Comment by AttackXiaoJinJin** [comment]
{"HeWeather": [{"aqi":{"city":{"aqi":"154","co":"1","no2":"30","o3":"181","pm10":"258","pm25":"77","qlty":"中度污染","so2":"16"}},
还有的
