### ISSUE TITLE
13章的全局获取context会造成内存泄漏

### ISSUE THREAD

**Issue by Nancy945** [guolindev/booksource#5]
Android Studio对这行有警告： private static Context context; 
“Do not place Android context classes in static fields;this is a memory leak(and also breaks Instant Run)”
希望能给一个最佳实践

**Comment by pcqpcq** [comment]
可以看看这两个地方对于 [官方做法](https://developer.android.com/training/volley/requestqueue.html#singleton) 的讨论：
尽量并没有消除这个警告，但是可以避免不正确的持有context造成的内存泄漏。所以我觉得官方的示例是一个最佳实践。

https://stackoverflow.com/questions/37709918/warning-do-not-place-android-context-classes-in-static-fields-this-is-a-memory/40235834#40235834

https://stackoverflow.com/questions/39840818/android-googles-contradiction-on-singleton-pattern/39841446#39841446

**Comment by guolindev** [comment]
并不会造成内存泄漏，因为这是一个Application Context，如果你执有的是一个静态的Activity Context，那就会内存泄漏的。Android Studio并没有智能地判断出来这是Application Context，所以这是一个误报，并没有任何影响，如果你看着觉得不舒服，可以在字段上加个这个注解  @SuppressLint("StaticFieldLeak")
