### ISSUE TITLE
书P388页判断3个权限有没有授权的小问题

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [guolindev/booksource#8]
在 Manifest.permission.xxxxxxx 前加 android.
另外书p389页 public class MyLocationListener implements BDLocationListener
该类要覆写
 void onConnectHotSpotMessage(String var1, int var2);

希望郭神在第三版中纠正这些小错误~

**Comment by tortoiseoncobweb** [comment]
这个赞同，我觉得可能是百度SDK更新了吧

**Comment by guolindev** [comment]
是的，因为SDK更新了。书上已经修复此问题，可以到这里查看勘误列表 http://www.ituring.com.cn/book/1841
