### ISSUE TITLE
书P542 添加service的打印问题

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [guolindev/booksource#9]
在showWeatherInfo方法中添加
Intent intent=new Intent(this, AutoUpdateService.class);
        startService(intent);

上下文是没有if...else相关代码的，书本的打印错误

**Comment by guolindev** [comment]
感谢反馈，已经确实是个勘误并在下一印中修复，所有勘误列表可以这里查看 http://www.ituring.com.cn/book/1841
